# Generated by Django 2.2.3 on 2019-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('level', models.IntegerField(default=2, max_length=2)),
                ('parent_id', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0, max_length=5)),
                ('type_id', models.IntegerField(default=0, max_length=5)),
                ('type', models.CharField(max_length=255, null=True)),
                ('disc', models.IntegerField(max_length=4, null=True)),
                ('disc_price', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('alt_tag', models.CharField(max_length=255, null=True)),
                ('type_id', models.IntegerField(default=0, max_length=5)),
                ('product_id', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('availability', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('product_id', models.BigIntegerField(default=0)),
                ('availability', models.BooleanField(default=1)),
                ('price', models.FloatField(default=0.0, max_length=12)),
                ('image', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0, max_length=5)),
            ],
        ),
    ]
