# Generated by Django 2.2.3 on 2019-08-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
