# Generated by Django 2.2.3 on 2019-08-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190804_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
